# Generated by Django 4.2.16 on 2026-07-13 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_type', models.CharField(choices=[('domain_full', 'Domain Full Scan'), ('domain_quick', 'Domain Quick Scan'), ('email_identity', 'Email Identity Scan'), ('scheduled', 'Scheduled Scan'), ('api_triggered', 'API Triggered Scan'), ('manual', 'Manual Scan')], default='domain_full', max_length=30)),
                ('trigger_source', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('api', 'API'), ('webhook', 'Webhook')], default='manual', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorizing', 'Authorizing'), ('authorized', 'Authorized'), ('discovering', 'Discovering'), ('reconnaissing', 'Reconnaissing'), ('correlating', 'Correlating'), ('scoring', 'Scoring'), ('intelligencing', 'Intelligencing'), ('reporting', 'Reporting'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('authorizing', 'Authorizing'), ('authorized', 'Authorized'), ('discovering', 'Discovering'), ('reconnaissing', 'Reconnaissing'), ('correlating', 'Correlating'), ('scoring', 'Scoring'), ('intelligencing', 'Intelligencing'), ('reporting', 'Reporting'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('suspended', 'Suspended')], max_length=20)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
                ('authorization_verified', models.BooleanField(default=False)),
                ('authorization_status', models.CharField(blank=True, choices=[('unverified', 'Unverified'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('authorized', 'Authorized'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired')], max_length=30)),
                ('authorization_scope', models.JSONField(default=list)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('celery_parent_id', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('current_phase', models.CharField(blank=True, max_length=30)),
                ('phase_started_at', models.DateTimeField(blank=True, null=True)),
                ('phase_progress', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(default=dict)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('high_count', models.PositiveIntegerField(default=0)),
                ('medium_count', models.PositiveIntegerField(default=0)),
                ('low_count', models.PositiveIntegerField(default=0)),
                ('info_count', models.PositiveIntegerField(default=0)),
                ('trust_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_status', models.CharField(blank=True, max_length=20)),
                ('dimension_scores', models.JSONField(default=dict)),
                ('confidence_level', models.PositiveSmallIntegerField(default=0)),
                ('reports_generated', models.JSONField(default=list)),
                ('notifications_sent', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('tags', models.JSONField(default=list)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Scan Job',
                'verbose_name_plural': 'Scan Jobs',
                'db_table': 'scanner_scanjob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('scan_type', models.CharField(choices=[('domain_full', 'Domain Full Scan'), ('domain_quick', 'Domain Quick Scan'), ('email_identity', 'Email Identity Scan'), ('scheduled', 'Scheduled Scan'), ('api_triggered', 'API Triggered Scan'), ('manual', 'Manual Scan')], default='domain_full', max_length=30)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='weekly', max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hour', models.PositiveSmallIntegerField(default=2)),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notification_channels', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_schedules', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Scan Schedule',
                'verbose_name_plural': 'Scan Schedules',
                'db_table': 'scanner_schedule',
                'ordering': ['next_run_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanPhaseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_logs', to='scanner.scanjob')),
            ],
            options={
                'verbose_name': 'Scan Phase Log',
                'verbose_name_plural': 'Scan Phase Logs',
                'db_table': 'scanner_phaselog',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='scanjob',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_jobs', to='scanner.scanschedule'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ScanComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_change', models.SmallIntegerField(default=0)),
                ('score_change_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('new_findings', models.PositiveIntegerField(default=0)),
                ('resolved_findings', models.PositiveIntegerField(default=0)),
                ('worsened_findings', models.PositiveIntegerField(default=0)),
                ('improved_findings', models.PositiveIntegerField(default=0)),
                ('new_critical', models.PositiveIntegerField(default=0)),
                ('new_high', models.PositiveIntegerField(default=0)),
                ('trend_direction', models.CharField(choices=[('improving', 'Improving'), ('declining', 'Declining'), ('stable', 'Stable'), ('unknown', 'Unknown')], max_length=20)),
                ('comparison_data', models.JSONField(default=dict)),
                ('previous_scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_comparisons', to='scanner.scanjob')),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='scanner.scanjob')),
            ],
            options={
                'verbose_name': 'Scan Comparison',
                'verbose_name_plural': 'Scan Comparisons',
                'db_table': 'scanner_comparison',
            },
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['domain', 'status'], name='scanner_sca_domain__0637f1_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['status', 'created_at'], name='scanner_sca_status_395f34_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['triggered_by', 'status'], name='scanner_sca_trigger_f63777_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['celery_task_id'], name='scanner_sca_celery__240c7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scancomparison',
            unique_together={('scan_job', 'previous_scan_job')},
        ),
    ]
