# Generated by Django 4.2.16 on 2026-07-13 19:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('pattern_id', models.CharField(max_length=20, unique=True)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('condition', models.JSONField()),
                ('logic_expression', models.TextField()),
                ('narrative_template', models.TextField()),
                ('affected_dimensions', models.JSONField(default=list)),
                ('remediation_priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=3)),
                ('remediation_steps', models.JSONField(default=list)),
                ('estimated_score_impact', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('applies_to_scan_types', models.JSONField(default=list)),
                ('required_layers', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Correlation Rule',
                'verbose_name_plural': 'Correlation Rules',
                'db_table': 'correlation_rule',
            },
        ),
        migrations.CreateModel(
            name='PatternMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('matched_findings', models.JSONField(default=list)),
                ('matched_signals', models.JSONField(default=list)),
                ('evaluation_result', models.JSONField(default=dict)),
                ('matched', models.BooleanField(default=False)),
                ('evaluation_time_ms', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='correlation.correlationrule')),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_matches', to='scanner.scanjob')),
            ],
            options={
                'verbose_name': 'Pattern Match',
                'verbose_name_plural': 'Pattern Matches',
                'db_table': 'correlation_patternmatch',
                'unique_together': {('scan_job', 'rule')},
            },
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pattern_id', models.CharField(choices=[('email_spoofing', 'Email Spoofing'), ('certificate_expiry', 'Certificate Expiry'), ('subdomain_takeover', 'Subdomain Takeover'), ('dns_misconfiguration', 'DNS Misconfiguration'), ('stale_http_security', 'Stale HTTP Security'), ('exposed_ports', 'Exposed Ports')], db_index=True, max_length=20)),
                ('pattern_name', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=10)),
                ('narrative', models.TextField()),
                ('short_description', models.CharField(max_length=255)),
                ('contributing_findings', models.JSONField(default=list)),
                ('contributing_signals', models.JSONField(default=list)),
                ('affected_dimensions', models.JSONField(default=list)),
                ('remediation_priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=3)),
                ('remediation_steps', models.JSONField(default=list)),
                ('estimated_score_impact', models.SmallIntegerField(default=0)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('is_suppressed', models.BooleanField(default=False)),
                ('suppression_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='scanner.scanjob')),
            ],
            options={
                'verbose_name': 'Correlation',
                'verbose_name_plural': 'Correlations',
                'db_table': 'correlation_correlation',
                'ordering': ['-risk_level', '-created_at'],
                'indexes': [models.Index(fields=['scan_job', 'risk_level'], name='correlation_scan_jo_8a4b02_idx'), models.Index(fields=['pattern_id'], name='correlation_pattern_23370d_idx')],
            },
        ),
    ]
