# Generated by Django 4.2.16 on 2026-07-13 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=64)),
                ('events', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_failure', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'db_table': 'api_webhookendpoint',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'db_table': 'api_webhookdelivery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(max_length=12, unique=True)),
                ('key_hash', models.CharField(max_length=64)),
                ('scopes', models.JSONField(default=list)),
                ('rate_limit', models.PositiveIntegerField(default=1000)),
                ('rate_limit_window', models.PositiveIntegerField(default=3600)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_public_api_keys', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_api_keys', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Public API Key',
                'verbose_name_plural': 'Public API Keys',
                'db_table': 'api_public_apikey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('requests_count', models.PositiveIntegerField(default=0)),
                ('requests_limit', models.PositiveIntegerField(default=10000)),
                ('scan_requests', models.PositiveIntegerField(default=0)),
                ('scan_limit', models.PositiveIntegerField(default=100)),
                ('report_requests', models.PositiveIntegerField(default=0)),
                ('report_limit', models.PositiveIntegerField(default=100)),
                ('metadata', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_quotas', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'API Usage Quota',
                'verbose_name_plural': 'API Usage Quotas',
                'db_table': 'api_usagequota',
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_params', models.JSONField(default=dict)),
                ('request_body', models.JSONField(default=dict)),
                ('response_status', models.PositiveIntegerField()),
                ('response_body', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_request_logs', to='accounts.organization')),
                ('public_api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='api.publicapikey')),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'db_table': 'api_requestlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='publicapikey',
            index=models.Index(fields=['organization', 'is_active'], name='api_public__organiz_c1f4f5_idx'),
        ),
        migrations.AddIndex(
            model_name='publicapikey',
            index=models.Index(fields=['key_prefix'], name='api_public__key_pre_cc402a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apiusagequota',
            unique_together={('organization', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['organization', 'timestamp'], name='api_request_organiz_6c8dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['public_api_key', 'timestamp'], name='api_request_public__2c76fa_idx'),
        ),
    ]
