# Generated by Django 4.2.16 on 2026-07-13 19:22

import apps.domains.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, validators=[apps.domains.models.validate_domain_format])),
                ('root_domain', models.CharField(db_index=True, max_length=255)),
                ('tld', models.CharField(max_length=50)),
                ('tld_category', models.CharField(choices=[('brand', 'Brand'), ('generic', 'Generic'), ('sponsored', 'Sponsored'), ('country_code', 'Country Code'), ('new_gtld', 'New GTLD'), ('unknown', 'Unknown')], max_length=20)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('financial_services', 'Financial Services'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('government', 'Government'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('media', 'Media'), ('energy', 'Energy'), ('other', 'Other')], max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('authorization_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('authorized', 'Authorized'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='unverified', max_length=25)),
                ('verification_method', models.CharField(blank=True, choices=[('dns_txt', 'DNS TXT Record'), ('html_file', 'HTML File Upload'), ('meta_tag', 'Meta Tag'), ('email', 'Email Verification')], max_length=20)),
                ('verification_token', models.CharField(blank=True, max_length=128)),
                ('verification_token_hash', models.CharField(blank=True, max_length=64)),
                ('verification_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_scope', models.JSONField(default=list)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('dns_resolves', models.BooleanField(default=None, null=True)),
                ('last_dns_check_at', models.DateTimeField(blank=True, null=True)),
                ('mx_records', models.JSONField(default=list)),
                ('name_servers', models.JSONField(default=list)),
                ('registrar', models.CharField(blank=True, max_length=255)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('privacy_protection', models.BooleanField(default=False)),
                ('current_trust_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_score_status', models.CharField(blank=True, max_length=20)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('last_scan_status', models.CharField(blank=True, max_length=20)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('is_monitored', models.BooleanField(default=True)),
                ('monitoring_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='weekly', max_length=20)),
                ('next_scheduled_scan', models.DateTimeField(blank=True, null=True)),
                ('alert_on_score_drop', models.PositiveSmallIntegerField(default=10)),
                ('alert_on_critical', models.BooleanField(default=True)),
                ('alert_on_new_subdomain', models.BooleanField(default=True)),
                ('alert_on_ssl_expiry', models.BooleanField(default=True)),
                ('alert_on_breach', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_domains', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='accounts.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'domains_domain',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainVerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('method', models.CharField(choices=[('dns_txt', 'DNS TXT Record'), ('html_file', 'HTML File Upload'), ('meta_tag', 'Meta Tag'), ('email', 'Email Verification')], max_length=20)),
                ('token', models.CharField(max_length=128)),
                ('token_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], max_length=20)),
                ('resolver_used', models.CharField(blank=True, max_length=50)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='domains.domain')),
            ],
            options={
                'verbose_name': 'Domain Verification Log',
                'verbose_name_plural': 'Domain Verification Logs',
                'db_table': 'domains_verificationlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('reason', models.TextField()),
                ('is_regex', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked Domain',
                'verbose_name_plural': 'Blocked Domains',
                'db_table': 'domains_blocked',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('settings', models.JSONField(default=dict)),
                ('domains', models.ManyToManyField(blank=True, related_name='portfolios', to='domains.domain')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Domain Portfolio',
                'verbose_name_plural': 'Domain Portfolios',
                'db_table': 'domains_portfolio',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['organization', 'authorization_status'], name='domains_dom_organiz_78c53d_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['next_scheduled_scan'], name='domains_dom_next_sc_2f8ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['root_domain'], name='domains_dom_root_do_7c6fcd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('organization', 'name')},
        ),
    ]
